config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing_pages'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_pages
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RubyGemsBootcamp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/static_pages/landing_pages.html.haml
%nav.navbar.navbar-expand-lg.bg-light
  .container-fluid
    %a.navbar-brand{:href => "#"}
      %i.fas.fa-home
      Navbar
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => "#"} Home
        %li.nav-item
          %a.nav-link{:href => "#"} Link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %li
              %a.dropdown-item{:href => "#"} Action
            %li
              %a.dropdown-item{:href => "#"} Another action
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Something else here
        %li.nav-item
          %a.nav-link.disabled Disabled
      %form.d-flex{:role => "search"}
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search
.container-fluid
  %h1
    Hello world
  = link_to "Privacy Policy",  privacy_policy_path, class: "btn btn-lg btn-warning"
  = link_to privacy_policy_path, class: "btn btn-lg btn-warning" do
    %i.fa-solid.fa-book
    Privacy Policy

app/views/static_pages/privacy_policy.html.haml
%h1 StaticPages#privacy_policy
= link_to "Home", root_path